### ISSUE TITLE
Investigating on Crosswalk and WKWebviews

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#100]
There is a lot of hype around Crosswalk and WKWebview is reputed to be supper fast but supper buggy.

Sort this out, measure performance and study the impact on Cobalt. Should we support this? should we base our work on this ?

**Comment by ggendre** [comment]
For iOS and WKWebivew we created `wkwebview` branches on Cobalt-iOS, Cobalt-Web, Cobalt-Web-Sources and iOS Catalog and Sidemenu App. No problem detected so far. seems to be promising :)

**Comment by Doc1faux** [comment]
Spotted issues on Catalog:
- LocalStorage with WKWebView:
    - Wrong value retrieved from popped controller while it has been changed by pushed one,
    - UI not responding after the stress Set test if the Check test has been done.
- Toast with XWalk: the 20 toasts in a row test only display toasts 4 by 4 (4, 8, 12, 16, 20)

**Comment by ggendre** [comment]
we must write an article on all this (before we forget it all ;) )

**Comment by ggendre** [comment]
WKWebviews is now used.
Crosswalk was not a big success and adds too much weight on the app
