### ISSUE TITLE
Catalog - ajax sample broken

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#101]
The sample AJAX call used in the Catalog Ajax page and in the Catalog Webservice Plugin page is not working anymore.

Because Google changed his image search API

**Comment by TDanielK** [comment]
Google Image search API has been replaced with Google Custom Search Engine (https://cse.google.com). This new API also allows to search for specific data types (including images) but is limited to 100 requests per day. Moreover, it requires a Google API key and a Search Engine ID (https://developers.google.com/custom-search/json-api/v1/overview#prerequisites). We could either create a Google API account for the demonstration purpose or let app developers enter their credentials.

**Comment by ggendre** [comment]
We have a google account for the mailbox behind contact@cobaltians.org. Use
it to create an api key. 100 req per day will be ok for the moment.
Le mar. 3 mai 2016 à 17:05, Tristan Daniel <notifications@github.com> a
écrit :

**Comment by TDanielK** [comment]
Ended up using [unsplash.it](https://unsplash.it) instead of Google APIs.
