### ISSUE TITLE
set cobalt view background colors from cobalt.conf

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#106]
It could be great to define the background color of the cobalt views from the cobalt.conf controllers configuration.

This enable apps to have a custom background, that will be seen when the webview is loading and when the user is pullToRefreshing.

A simple `backgroundColor : #008FD6` in the cobalt.conf would do the job.

Use the same colors detection as we used in bars

- [x] Handle on iOS
- [x] Handle on Android
- [x] Add a sample of this in Catalog App
- [x] Test navigation/dark simple page and PTR/coulouredPTR page on Android for the win
- [x] Write a quick blog post
- [x] merge feature-106 on catalog develop.
- [x] rename it form `background` to `backgroundColor` on web sample
- [x] rename it form `background` to `backgroundColor` on iOS
- [x] Apply color on root view instead of the WebView and apply clear color for this one on iOS
- [x] rename it form `background` to `backgroundColor` on Android
- [x] update sidemenu sample to use it aswell
- [x] Test Android Catalog and Android Sidemenu Sample because @ggendre is having graddle issues on his mac. Then, move to "Done".
- [x] fixed cobalt.conf on develop line 10 ""backgroundColor": "#19E9FF"," kill the comma !

**Comment by Doc1faux** [comment]
Default value: white

**Comment by Doc1faux** [comment]
Done iOS side

**Comment by ggendre** [comment]
reopened for the com part and updated issue with missing tasks

**Comment by ggendre** [comment]
created a branch `feature-106` for web, android and ios Ctalaog sample.

iOS Catalog works great. haven't teste Android Catalog yet.

**Comment by ggendre** [comment]
added tasks to change attribute name from `background` to `backgroundColor`.

**Comment by Myrdhinn** [comment]
Test Android on branch develop  Catalog and SideMenuSample - OK
Added task to fix error Web side in cobalt.conf
