### ISSUE TITLE
Enhance building from sources

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#107]
The framework script used when we build a Cobalt app using the iOS Cobalt sources is currently writing the .framework and .bundle files on the user desktop.

The app developper has to remove them by hand if he doesn't want a fail on the next build.

Enhance this by removing previous file on each build and creating it in the Cobalt folder instead of the user desktop.

**Comment by Doc1faux** [comment]
Now, `.framework` and `.bundle` files are located in this folder: `${BUILD_DIR}/${CONFIGURATION}-all`

The `CONFIGURATION` var can take 2 values: `Debug` and `Release`
The `${BUILD_DIR}` var relies on the `CONFIGURATION` value:
- `Debug`: `Build/Products`,
- `Release`: `Build/Intermediates/ArchiveIntermediates/${TARGET_NAME}/BuildProductsPath`.

The `TARGET_NAME` var is what you have chosen to build with Xcode (see picture below in RED or BLUE) 

![target-1](https://cloud.githubusercontent.com/assets/2175246/17300184/99389e84-5811-11e6-8710-a6d73eee21b3.png)
![target-2](https://cloud.githubusercontent.com/assets/2175246/17300183/99324502-5811-11e6-9140-eb0c912d8b9a.png)

Finally, this folder is located in the `DerivedData` folder whose you can find its path in the `Preferences` pane of Xcode (see picture below)
![deriveddata](https://cloud.githubusercontent.com/assets/2175246/17299477/c1aee09c-580e-11e6-82df-47c2662d2cc3.png)

So, in the pictures above, the paths could be:
- `/Users/${USER}/Library/Developer/Xcode/DerivedData/Catalog-${ID}/Build/Products/Debug-all`
- `/Users/${USER}/Library/Developer/Xcode/DerivedData/Catalog-${ID}/Build/Intermediates/ArchiveIntermediates/Catalog/BuildProductsPath/Release-all`

**Comment by Doc1faux** [comment]
Moreover, since I moved the files there, it seems I did not need to remove them manually nor with the embedded script.
