### ISSUE TITLE
Add iosScrollToTop in cobalt.conf

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#109]
Enable developer to activate the scroll to top gesture (a simple tap in the status bar) on the controller he wants.

Handle `iosScrollToTop:true/false` in cobalt.conf on iOS. Default should be false.

This would enable scroll to top on the Cobalt webview only. We can not enable this if the developper has other scrolling native components in his view

- [x] Handle on iOS
- [x] Add a sample of this in Catalog App
- [x] Write a quick blog post
- [x] Set default to true
- [x] Update cobalt.conf doc

**Comment by ggendre** [comment]
I think we should change default to true. what do you think ?

**Comment by Doc1faux** [comment]
You're a weathercock :P You told me that Cobalt should not "surpass" the native by enabling the WebView to respond to the scrollsToTop and now, you do not want?

**Comment by ggendre** [comment]
as seen together in the doc, the default value should be true
