### ISSUE TITLE
CLI - enhance for real projects architecture

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#111]
The current CLI is creating an iOS and Android folder. Both have submodules for Cobalt. Both have a www folder that contains web sources.

This last point is not good. Because in real world case, the www folder is often common (with a submodule or a symlink) and the dev don't want to have to copy/paste the www folder.

I suggest that the CLI create an Android, an iOS and a www folder at the root of the project file tree and that we add a small `cobaltians myApp build` command to copy the www folder at the good place.

The CLI should also remove the .git files of the project, so that when the user is starting to dive into code and move things along, he does not have a mass of removed/added files when doing a `git status`

**Comment by lduboeuf** [comment]
+1, i think that having a clean directory structure and avoiding duplicate files help to clarify users. Not agree of using another command to make it work, is it possible to do it with platform's package manager (gradle & co) ?

**Comment by lduboeuf** [comment]
for me it is a priority task because the CLI is the starting point for anyone who want to test cobalt.

**Comment by ggendre** [comment]
>Not agree of using another command to make it work,

- iOS is abled to have the www folder outside the app folders. 
- Android need the www folder to be in assets

this gives us 3 choices : 
- Use the android www folder as the only www folder and link the ios www to it in the ios project. (dirty and what if the user wants only an iOS app)
- Have an external www folder and run a command like `cobaltians prepare myApp` to put it at the right place (that is what cordova does)
- symbolic inks. but it doesn't work on Windows.

**Comment by ggendre** [comment]
Having a `prepare` command will simplify other things : 
- the cobalt.js file could be copied by the script so the dev won't have to bother about android VS ios version of this file.
- It will pave the way for a "browser" platform aside of ios and android (#63) ;)
- and maybe we could have a debug platform aside of them and use it to avoid the need of debugInBrowser boolean for testing ?

**Comment by lduboeuf** [comment]
i thought symlink was ported to windows from Vista distribution. Is it possible to execute `cobaltians prepare myApp` at build time in gradle and iOS equivalent ?

**Comment by ggendre** [comment]
You are right there may be a solution for git symlinks on windows : more about it here. http://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows
