### ISSUE TITLE
nativeBars - use themeEditors colors

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#113]
Cobalt Android is not using the good theme colors. We should match the colors visible in the theme editor of the new Android Studio.

Update cobalt theme to use them

**Comment by ggendre** [comment]
> roxane.paurobally [9:33 AM, today]  
> I finished this issue. it will need some tests/review before merging it

assigned to @Doc1faux for review :)

**Comment by Doc1faux** [comment]
I have implemented a mix between @xarone & @Myrdhinn ways, fixing some attribute issues on specific versions and some parsing and integrated it in Cobalt, modifying a bit the code of bars handling & font handling.
