### ISSUE TITLE
Enable access to pubsub from the native side

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#118]
Enable the native side to easily access the pubsub plugin through Cobalt with the same API as the web : `subscribe`, `publish`, `unsubscribe`. 
- [ ] Enable access to pubsub on Android
- [ ] Enable access to pubsub on iOS
- [ ] Add sample in catalog on Android
- [ ] Add sample in catalog on iOS
- [ ] Enhance wiki documentation on Cobalt Storage for Android
- [ ] Enhance wiki documentation on Cobalt Storage for iOS
- [ ] Create a blog article that present the feature

**Comment by Doc1faux** [comment]
New issue incoming with this feature and replacing cobalt events handling with PubSub
