### ISSUE TITLE
nativeBars - ios back button color

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#125]
@Doc1faux any way to fix the back button color ?

![bugiosbackbuttoncolor](https://cloud.githubusercontent.com/assets/534697/16594204/9f88f848-42e9-11e6-93cc-da2883acae65.gif)

**Comment by Doc1faux** [comment]
@ggendre TODO: merge to master

**Comment by ggendre** [comment]
ok fixed in 0.6. will wait the release to merge
