### ISSUE TITLE
SideMenu - random issue with onPageShown

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#126]
at first launch, when installing the app for the first time, it can occur that the main webview miss the onPageShown event.

We found out that CobaltIsReady seems to be sent before the web page is fully loaded. 

@ggendre though it should not be a problem as soon as scripts and DOM are loaded but it may be a mistake.
- [ ] ggendre wants to try to move scripts in `<head>`
- [ ] Doc1faux has a patch : waiting for webviewFullyLoaded event
- [ ] we must ensure that this patch does not wait for all images to load in the webview.
- [ ] ggendre may fix the web instead to ensure cobalt.js and all scripts are loaded

**Comment by ggendre** [comment]
I think we should at least wait for the cobaltIsReady event on the iOS side. That is what we are doing in the Android version. I don't know why it is not (anymore?) what we do on iOS.

**Comment by Doc1faux** [comment]
It is what we do on iOS too...
But as it is described in the issue, the "webviewFullyLoaded" delegate method is potentially called after the `cobaltIsReady` Web is received and in this case, the Native-to-web messages queue is resumed before the WebView is fully loaded, so I assume messages sent in this short range of time are simply lost.

**Comment by ggendre** [comment]
did not succeed to reproduce this morning 😢
