### ISSUE TITLE
fontToCobalt - Not well parsed

### ISSUE THREAD

**Issue by Doc1faux** [cobaltians/Cobalt#128]
At least, on the last version of FontAwesome, the CSS file can define multiple character classes for a single character content (see below).

```
.fa-flash:before,
.fa-bolt:before {
  content: "\f0e7";
}
```

In this case, the parsing script fails because it only import the first character class for the  character content in the glyph dictionary generated.

**Comment by RoxaneSarahPaurobally** [comment]
Fixed: fontToCobalt now takes into consideration multiple selectors https://github.com/Cobaltians-Fonts/fontToCobalt/commit/7e0020ce622a97be7957bc5e8d5ff2e24e155bdb

**Comment by Doc1faux** [comment]
Many thanks @RoxaneSarahPaurobally! :) I was not hoping your fix but finally, I will generate the FontAwsome classes tomorrow to check it ;)

**Comment by RoxaneSarahPaurobally** [comment]
Okay :), if it is working, feel free to close the issue.

**Comment by Doc1faux** [comment]
Fix is working, closing...

FontAwesome has aliases for many characters (see characters with "(alias)" in its [list](http://fontawesome.io/icons/))
