### ISSUE TITLE
sidemenu icon not shown after switching page

### ISSUE THREAD

**Issue by lduboeuf** [cobaltians/Cobalt#132]
help please,

when switching pages from sidemenu, icon disappear. Probably i'm doing it wrong ;-)
`https://github.com/lduboeuf/kikou-cobalt/tree/sidemenu`

**Comment by ggendre** [comment]
thanks for reporting.
Anyway it has been already fixed on develop branch. This will come with the 0.6 release.

If you want to try the develop branch : 
- just add ` develop` at the end of the CLI command (`cobaltians create myProjectName SideMenu develop`)
- or if you already git cloned the project, `git checkout develop` and `git submodule update --init`
