### ISSUE TITLE
[FAQ] Rails example

### ISSUE THREAD

**Issue by kirantpatil** [cobaltians/Cobalt#133]
Hi,

Please show me a sample example of how to use with RubyonRails.

How it is different from Rails [Turbolink adaptors](https://github.com/turbolinks/turbolinks-android) ?

Thanks.

**Comment by ggendre** [comment]
Hi, thank for your comment.

You can see similarity between turbolink adaptors (especially when [they explain they use native navigation between pages](https://github.com/turbolinks/turbolinks#application-visits)) and the cobalt navigation. 
But I guess that when they do this, the app is still a single-page app, loaded one time in the first webview and a second time in the pushed new webview. The whole html/css/js is loaded twice. We tried this with Cobalt too for a client and it works but Cobalt allows you to have different html/css in each webview and it's a great improvement to performances.

Cobalt is not a server side tool at all so we can not really provide an example with RubyOnRails. It does not force you to use one or another javascript framework or sever side language or tool. you can build your app the way you want (or are used to) with plain old javascript or any framework you like.

Another thing Cobalt has and Turbolink have not is the unified [nativeBars](https://github.com/cobaltians/Cobalt/wiki/nativeBars). Wich is great to handle bars for iOS and Android but does not include a full web version to use as an alternative on a website.

As far as I understand (I haven't tried it), Turbolink is a kind of jQueryMobile with a native adapter for navigation. This is smart when you want your website to run in a mobile app. If your mobile app needs more than just navigation (access to more native stuff), it won't be enough I guess.

Hope this helps you understand our tool in comparaison with turbolink.
Cheers,

**Comment by kirantpatil** [comment]
Yup, thanks a lot for clarifying.
