### ISSUE TITLE
allowing parent webview to close weblayer

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#136]
On iOS, calling `cobalt.webLayer('dismiss')` on parent dismiss the weblayer.
On Android it works only if called from the weblayer webview itself.

I will propose here a small change that does the job

**Comment by ggendre** [comment]
#135 #136 #137 all have their branche but are also merged into an experimental branche `issues-135-136-137` about weblayers fixes

**Comment by Doc1faux** [comment]
I disapprove this commit https://github.com/cobaltians/Cobalt-Android/commit/81844158f89133dd4db6e7398476658938f34dea

**Comment by Doc1faux** [comment]
Done in [weblayer-experiments](https://github.com/cobaltians/Cobalt-Android/tree/weblayer-experiments) branch
