### ISSUE TITLE
android bars events are sent to the wrong fragment.

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#137]
When we want to combine nativebars and weblayer, if the parent view is settings the bars, clicking on a bar button will actually send the button event to the weblayer fragment instead of the parent fragment.

I've made a "fix" but it's a bit dirty, I will need some advice on how to do this better. (commit with the incoming)

**Comment by ggendre** [comment]
#135 #136 #137 all have their branche but are also merged into an experimental branche `issues-135-136-137` about weblayers fixes

**Comment by Doc1faux** [comment]
I disapprove this commit https://github.com/cobaltians/Cobalt-Android/commit/59c2cbcbc49079e383182c2ee8cb18923d595fd1

**Comment by Doc1faux** [comment]
Fixed byt [this commit](https://github.com/cobaltians/Cobalt-Android/commit/cc20d9f30700e770fb6d22f9091914363cbeedcf). Done in [weblayer-experiments](https://github.com/cobaltians/Cobalt-Android/compare/weblayer-experiments) branch
