### ISSUE TITLE
ios - Keep Javascript context when navigating.

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#138]
If you navigate from one HTML page to another without cobalt.navigate.push, with an old `a href` link for example, Cobalt won't work on the next page.

It is because the javascript context window.CobaltViewController is lost. After some digging we found that re-setting the context on webViewDidFinishLoad did the job.

I will commit here the patch for review

**Comment by ggendre** [comment]
will create a temporary branche issues-135-138 with weblayer enhancements for iOS too.

**Comment by Doc1faux** [comment]
I do not approve this commit https://github.com/cobaltians/Cobalt-iOS/commit/f3cd28b00a54e2c81ee01d5b0d5e7b1e6d56dbed.
Fix is coming.

**Comment by Doc1faux** [comment]
Done in [weblayer-experiments](https://github.com/cobaltians/Cobalt-iOS/tree/weblayer-experiments) branch
