### ISSUE TITLE
send weblayer loading status to parent webview

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#142]
When loading an external webview it can be useful to be notified when weblayer page is loading and when it finishes loadind.

I will submit code here that sends events `onWebLayerLoading` and `onWebLayerLoaded` in addition to the existing `onWebLayerDismissed` event to the parent webview.

It will be merged with #135 #136 #137 and #138 into a `weblayer-experiments` branche

- [x] iOS
- [x] Android

**Comment by Doc1faux** [comment]
I disapprove this commit https://github.com/cobaltians/Cobalt-iOS/commit/0da1c2e2c0f0eab863ba6dc57c2976f447a697a1.
Fix is coming.

**Comment by Doc1faux** [comment]
I disapprove this commit too https://github.com/cobaltians/Cobalt-Android/commit/386af4af4dc20c5587a69a161b4e47b9465200cc.
Fix is coming...

**Comment by Doc1faux** [comment]
Done in [weblayer-experiments](https://github.com/cobaltians/Cobalt-Android/compare/weblayer-experiments) branch
