### ISSUE TITLE
ios core : ios / JS exchanges encoding issue with non UTF8 chars

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#16]
When sending an Emoji from native side to the web, the string encoding of the JSON is crashing.
Because Emoji are not in the scope of UTF8 and the ios isValidJSON method is not warning about any problem.

**Comment by Doc1faux** [comment]
@ggendre Fixed or not fixed? That is the question...

**Comment by Doc1faux** [comment]
Seems to work
