### ISSUE TITLE
Prefix core cobalt events with "cobalt:" 

### ISSUE THREAD

**Issue by ggendre** [cobaltians/cobalt#160]
- [ ] doc !

- onPageShown -> cobalt:onPageShown
- onAppStarted -> cobalt:onAppStarted
- onAppBackground -> cobalt:onAppBackground
- onAppForeground -> cobalt:onAppForeground
- onBackButtonPressed -> cobalt:onBackButtonPressed
- pullToRefresh -> cobalt:**onP**ullToRefresh **(!! ajout du "on" en début de nom)**
- infiniteScroll -> cobalt:**onI**nfiniteScroll  **(!! ajout du "on" en début de nom)**

Note : Les events suivant seront tirés par le pubsub. c'est donc le nom du channel et pas le nom de l'event dont il s'agit : 
- onAppStarted -> cobalt:onAppStarted
- onAppBackground -> cobalt:onAppBackground
- onAppForeground -> cobalt:onAppForeground

**Comment by Doc1faux** [comment]
All done on iOS & Android
