### ISSUE TITLE
queue navigation calls on ios

### ISSUE THREAD

**Issue by cobaltians** [cobaltians/Cobalt#18]
if we chain push and pop calls too fast on ios and if the page transitions animations are not finished, the navigation controller can fall into an unstable state complaining like this

    nested push animation can result in corrupted navigation bar
    Finishing up a navigation transition in an unexpected state. Navigation Bar subview tree might get corrupted.
    Unbalanced calls to begin/end appearance transitions for <FCMyViewController: 0x17dac270>.

**Comment by ggendre** [comment]
planned for 0.5.1
