### ISSUE TITLE
iOS alert collision

### ISSUE THREAD

**Issue by mywaystar** [cobaltians/Cobalt#23]
Hi guys!

There's is a collison beetween cobalt alerts & native alerts on iOS.

How to reproduce:
-----------

Create a native alert with a delegate on your native part.
Create a cobalt alert on your web part.

Your callback on your web part should be never called

**Comment by ggendre** [comment]
planned for 0.5.1

**Comment by Doc1faux** [comment]
Unable to reproduce.

Cobalt keeps track of its own shown AlertViews with auto-generated tags, checking in the AlertViewDelegate method `alertView:clickedButtonAtIndex:` if it corresponds to a Cobalt fired AlertView, getting the callback and send it.

**Comment by Doc1faux** [comment]
My bad, it can happens on iOS7 and older if you add a tag to your native UIAlertView which is the same as a Cobalt fired one...

**Comment by Doc1faux** [comment]
"Partially" fixed.
Auto-generated tag was incremental and started to 1...
Now it is generated from an [UUID string](https://developer.apple.com/library/ios/documentation/CoreFoundation/Reference/CFUUIDRef/).

Collision are still able to happen but far less frequently...
Right way will be to create CobaltAlertViews...
