### ISSUE TITLE
sendEvent: sent object type is limited to JSONObject on Android

### ISSUE THREAD

**Issue by baptistejamin** [cobaltians/Cobalt#24]
On iOS, you can send whatever you want as your Event data. For instance, you can send a string as data

[self sendEvent:"test" withData:@"aString" andCallback:nil];

On Android, you have the choice between, JSON, and... JSON.

**Comment by ggendre** [comment]
planned for 0.5.1

**Comment by ggendre** [comment]
will be obsolete with next pubsub release
