### ISSUE TITLE
Plantage de l'application

### ISSUE THREAD

**Issue by soritabu** [cobaltians/cobalt#26]
Bonjour,

Je viens de creer un projet avec votre framework mais lors du lancement de l'application sur un terminal ou un émulateur l'application se plante à l'ouverture.

J'ai aussi testé avec votre HelloWorld mais même résultat...

Lors de l'exécution de l'application, le LogCat me reporte les erreurs ci-dessous

![capture](https://cloud.githubusercontent.com/assets/10819309/6010625/49389a32-ab34-11e4-8f91-d5b72c60e85f.PNG)

Merci d'avance pour votre réponse

**Comment by Doc1faux** [comment]
Bonjour, 

Je vais regarder votre problème dans la journée.

Pourriez-vous me préciser l'IDE que vous utilisez, si votre SDK Android est à jour et les librairies de support installées et ajoutées à votre projet ?

En attendant votre réponse, je vais vérifier si l'import de nos projets de démonstration fonctionnent toujours correctement.

Merci d'avance.

**Comment by soritabu** [comment]
Bonjour,

J'utilise eclipse luna 4.4.1, avec la dernière version du SDK Android (24.0.2).

Pour ce qui est des librairies de supports, j'importe android-support-v7-appcompat.jar et android-support-v4.jar au niveau du projet librairies cobalt et de notre projet.

Merci pour votre aide

**Comment by Doc1faux** [comment]
Je viens tout juste de pousser 2 nouveaux commits sur la branche master, pour Cobalt et le projet HelloWorld, qui devraient solutionner le problème.

En effet, les projets Cobalt et HelloWorld de cette branche ne ciblaient pas la dernière version d'Android et les Activities du projet HelloWorld n'utilisaient pas des thèmes héritant de ceux de la librairie AppCompat, cause principale du crash que vous avez subit.

Faites donc attention sur ce dernier point à ce que vos thèmes définis dans les fichiers styles.xml ou autres héritent bien des thèmes Theme.AppCompat.* et non des thèmes android:Theme.*.

Concernant la configuration de votre projet, sous Eclipse, je vous recommande de : 
    - copier puis importer le projet AppCompat situé dans le dossier de votre SDK (extras > android > support > v7 > appcompat) et vérifier que les librairies privées sont bien exportées (clic droit sur le projet > Propriétés > Java Build Path > Order and Export > Android private libraries coché),
    - importer le projet Cobalt et mettre à jour au besoin le chemin vers la librairie AppCompat (clic droit sur le projet > Android > Library),
    - importer le projet HelloWorld ou votre projet.

Tenez-moi au courant si jamais ma réponse ne solutionne pas votre problème.

**Comment by soritabu** [comment]
Merci beaucoup pour votre aide, tout fonctionne bien maintenant !

Ps : Je reviendrais surement vers vous durant les deux semaines à venir en cas de problème lors du développement ;)

**Comment by Doc1faux** [comment]
Ravi d'apprendre que votre projet fonctionne parfaitement dorénavant :)

Je clos le bug.

N'hésitez pas à nous remonter tout problème que vous rencontrez sur le bug tracker de GitHub.
Pour toute autre question, vous pouvez nous contacter via notre forum https://groups.google.com/forum/?hl=fr#!forum/cobaltians.

Cordialement.
