### ISSUE TITLE
Menu sidebar pour application Android

### ISSUE THREAD

**Issue by ApprentiCobaltian** [cobaltians/Cobalt#27]
Bonjour,

J'essaye de mettre en place un menu du même type que celui utilisé dans l'application "CodeDArmor" (appli utilisable après l'avoir mise à jour avec la version actuelle de Cobalt) mais je ne comprends pas tout...

Ce que pense avoir compris (et encore...) : 
- La page "sideMenu.html" génére le menu et le script permet d'envoyer l'événement qui permet le changement de fragment du côté natif de l'application,
- Le fragment "SideMenuFragment.java" reçoit l'événement de la page "sideMenu.html" pour mettre à jour le fragment à afficher.

Ce que je n'ai pas compris :
- Comment les pages html appellent la page "sideMenu.html",
- Dans "SideMenuFragment.java", quelle est l'utilité de la fonction getpage().

	protected String getPage() {
		return "sideMenu.html";
	}

Je suis débutant en Android et donc par conséquent aussi avec Cobalt. J'ai saisi les principes du framework avec les événements pour passer du web au natif et inversement mais je suis perdu pour la réalisation du menu...

Merci pour votre aide,

JB

**Comment by ApprentiCobaltian** [comment]
Je viens de comprendre qu'il faut utiliser les fichiers XML du dossier "layout" et que le fragment lié au menu appel la page HTML du menu. Mon menu fonctionne mais ça reste flou pour moi...

**Comment by ggendre** [comment]
Bonjour JB,

On a prévu un plugin sidemenu pour faire ça au propre un jour. Pour l'instant il faut encore utiliser des compétences Web et Android.

Si tu veux déclencher l'apparition du sidemenu depuis la page web il faut je pense envoyer un evenement depuis le web (si le header de ta page est en web?), puis, dans la partie Android, catcher cet evenement et déclencher l'ouverture du side menu.

Pour cette dernière action ça dépendra de la librairie ou du composant que tu utilise côté android pour ton sidemenu.

Je ne suis pas un pro en Android donc je laisse @Doc1faux le soin de t'aider + s'il a des idées :)
Bon courage

Guillaume

**Comment by Doc1faux** [comment]
Bonjour JB,

J'ai mis à jour l'application Code d'Armor afin de la simplifier et d'ajouter le bouton d'ouverture/fermeture du side menu.

Pour expliquer rapidement le fonctionnement du side menu.
Il est défini dans le layout "activity_list.xml" de l'activity ListActivity avec l'identifiant "drawer_layout".
Il contient un conteneur principal "fragment_container" qui héberge le fragment Cobalt courant (au démarrage, le contrôleur ListView : classe ListFragment, page eventsList.html).
Il contient également un fragment Cobalt "SideMenuFragment" qui héberge le fichier "sideMenu.html" qui génère le side menu et envoie l'évènement de clic sur un item de la liste à ce même fragment pour remplacer le fragment courant.

Maintenant, pour répondre à tes questions : 
La page "sideMenu.html" est isolée, les autres pages ne l'appellent pas, tout est géré en natif.
Dans "SideMenuFragment.java", la fonction surchargée getPage permet au natif de définir la page Web chargée à la création du fragment.
Enfin, concernant le bouton, il est ajouté et géré par l'activity "ListActivity" dans les sections "LIFECYCLE" et "MENU" de mes commentaires.

**Comment by ApprentiCobaltian** [comment]
Bonjour Doc1faux,

Merci pour ton aide, j'ai réussi à implémenter le menu pour mon application. Cependant il me reste quelques questions : 
- Comment lier une page HTML à un fragment ? Lorsque je créé une nouvelle page HTML, chaque sendEvent est envoyé au fragment ListFragment mais le menu lui est lié au SideMenuFragment. J'aimerai pouvoir envoyé un event d'une page HTML qui me permet de changer de fragment (simuler un changement de page - redirection - lorsque l'utilisateur s'authentifie),
- J'aimerai pouvoir lier le menu à une image d'une page HTML (cliquer sur l'image pour ouvrir ou fermer le menu). Je voulais utiliser onOptionsItemSelected(MenuItem item) mais je ne sais pas ce qu'il faut passer en paramétre...

Merci de votre aide,

JB

**Comment by mywaystar** [comment]
Egalement, une app multipage, ça serait cool

**Comment by ggendre** [comment]
Hello

Juste pour info on a release un sample SideMenu il y a quelques semaines. Plus d'infos sur le blog [par ici](http://cobaltians.org/blog/sidemenu-sample-inited/)

**Comment by ggendre** [comment]
je clos l'issue, si il reste le moindre soucis, ne pas hésiter à la r'ouvrir !

**Comment by ApprentiCobaltian** [comment]
Bonjour Guillaume,

Merci de m'avoir tenu informer. Maintenant que j'ai un peu plus de temps,
je pense me replonger sur Cobalt. Je suis curieux de voir l'évolution :)

À bientôt sur le forum sûrement :)
Le 12 janv. 2016 18:54, "Guillaume Gendre" <notifications@github.com> a
écrit :
