### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by soritabu** [cobaltians/cobalt#28]
Bonjour,

Est-il possible de mettre en place des notifications avec Cobalt ou faut t'il utiliser du code android ?

Merci d'avance.

Cordialement,
Geoffrey

**Comment by ggendre** [comment]
Bonjour,

C'est un plugin que nous avons prévu de réaliser, nous avons déjà du code existant mais il y a encore du boulot pour en faire un plugin sympa. Nous avons prévu de nous y atteler dans les 6 prochains mois.

En attendant il faut malheureusement que vous implémentiez vous-même le code Android correspondant. Pour ça il y a [la doc Android](http://developer.android.com/google/gcm/gs.html). Côté serveur, selon la taille de votre application ça vaut parfois le coup de passer par un service payant tel que [EasyPush](http://www.easy-push.com/features/) ou Capptain. Si vous n'avez qu'une petite application un script PHP ou Python + une petite base de donnée fera l'affaire mais vous réservera + de surprises.

Bon courage pour ces travaux :)
Guillaume

**Comment by ggendre** [comment]
Je ferme ce thread mais n'hésitez pas à revenir vers nous si vous avez des questions sur le sujet.
