### ISSUE TITLE
Problème LocalStorage

### ISSUE THREAD

**Issue by soritabu** [cobaltians/Cobalt#29]
Bonjour,

J'essaie d'utiliser les fonctions de stockage que vous mettez à dispositions pour garder mes données sous forme JSON dans l'application lors de la navigation.

Mon problème est lors du test de l'existance de ses données cela me revoie null à chaque changement de page.

Mon code de test :
if(cobalt.storage.getItem('eventsDataJson', 'json') == null){
        	cobalt.sendEvent("getEvents");
}
else{
        	var eventsDataJson = cobalt.storage.getItem('eventsDataJson', 'json');
        	displayEvents(eventsDataJson);
}

**Comment by ggendre** [comment]
Bonjour,

Nous utilisons cette fonctionnalité tous les jours sur un grand nombre de devices donc je suis étonné qu'elle ne fonctionne pas pour vous.

Comment enregistrez vous les données? il faut utiliser notre cobalt.storage.setItem, comme indiqué dans notre [documentation](https://github.com/cobaltians/cobalt/wiki/localStorage), même si tu vous n'y mettez qu'une string et que ça ne parait pas nécessaire : pour android, le localStorage ne fonctionne pas bien et nous l'avons complètement remplacé.

Par exemple, vu que vous semblez y stoquer du JSON il faut faire quelquechose comme ça :
    cobalt.storage.setItem('eventsDataJson',  myEventsArray, 'json')

et ne pas oublier le type "json", sinon ça stoque ça de la mauvaise façon.

    cobalt.storage.setItem('ffezfze', [1,2,3], 'json')
    cobalt.storage.getItem('ffezfze', 'json')
    [1, 2, 3]

    cobalt.storage.setItem('ffezfze', [1,2,3])
    cobalt.storage.getItem('ffezfze', 'json')
    null

Ah bah tiens, n'est-ce pas ça votre erreur ?

De mon côté je viens de voir que la version web/ios peut partir en erreur quand on fait les deux dernières lignes de mon code ci-dessus. Je vais corriger ça, même si c'est hors du fonctionnement normal.

**Comment by ggendre** [comment]
Corrigé dans Cobalt 0.4.1 qui sort ce jour (release en cours).
