### ISSUE TITLE
HelloWorld PullToRefresh iOS visual bug

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#31]
In the iOS HelloWorld Sample, when a user starts making a pullToRefresh gesture, a space appears as soon as he starts to pull, between the top of the screen and the webview.

This is not related to the navBar, because if I comment the line containing `[self.navigationController setNavigationBarHidden:YES];`, the bug is still here, between the navBar and the content.

This bug only appears on iphone devices, not ipads. It does not exist in the other sample, the Catalog app.

Probably a small xib bug that you may not reproduce in your projects.

**Comment by ggendre** [comment]
We will fix this one, on the 0.3 branche, as soon as our iOS dev comes back from outer space (in 2 weeks probably). By the meantime if you have any clues on this one, you are more than welcome to help us ;)

**Comment by ggendre** [comment]
I noticed it appears only on iPhone 5 : iPad and iPhone 6 are working fine...

**Comment by ggendre** [comment]
this should be fixed on Cobalt branch dev-nativeBars I guess ?

**Comment by Doc1faux** [comment]
Fixed. Available in the next release!
