### ISSUE TITLE
Make a Cobalt "Support" Library

### ISSUE THREAD

**Issue by baptistejamin** [cobaltians/Cobalt#33]
Hi guys!

I suggest to keep the Cobalt Core small, to have a compatibility Library, essentially for the web code part.

**Comment by ggendre** [comment]
I suppose you talk about things like the DatePicker and placeholder javascript/CSS to make it work on iOS ?

or maybe the iOS6 support in the iOS cobalt.js ?

**Comment by ggendre** [comment]
DatePicker is now being removed. Only a few patches remain for webviews. So this should not be necessary.
