### ISSUE TITLE
Cannot install...

### ISSUE THREAD

**Issue by richnourichnou** [cobaltians/Cobalt#34]
Hello

I'll try to install Cobalt, but...
```
sudo npm install -g cobaltians 
```
--> OK

```
cobaltians create cobaltiansApp cobaltiansHelloWorld
Would you like to create an iOS app y/n  (default: y): 
Would you like to create an Android app y/n  (default: y): n
Info cloning https://github.com/cobaltians/cobalt.git
Success repository https://github.com/cobaltians/cobalt.git cloned
Info cloning https://github.com/cobaltians/Samples-cobaltiansHelloWorld-ios.git
Username for 'https://github.com': richnourichnou
Password for 'https://richnourichnou@github.com': 
Error cannot clone the repository at https://github.com/cobaltians/Samples-cobaltiansHelloWorld-ios.git
```
What can I do ?
Tks...

**Comment by ggendre** [comment]
hi !

The second parameter of the "create" command must be an existing sample App.

You can use `cobaltians create cobaltiansApp HelloWorld` which will uses this sample to create your app : `https://github.com/cobaltians/Samples-HelloWorld-android`

You can also use `Catalog` which is a more complex sample.

have fun!

**Comment by richnourichnou** [comment]
Ok, i understand

Thank's

**Comment by ggendre** [comment]
Closing the issue. Everything worked the way you wanted ?
