### ISSUE TITLE
Problems with node v4

### ISSUE THREAD

**Issue by andresetevejob** [cobaltians/Cobalt#35]
Hi All, 
I have a error when i want to create my app with cobalt.this is the error message : 

Error { [Error: Cannot find module '../build/Debug/nodegit.node'] code: 'MODULE_
NOT_FOUND' }

**Comment by ggendre** [comment]
Hi,

That's weird because nodegit should have been installed when installing cobaltians CLI. You can try to uninstall and reinstall cobaltians :

    sudo npm uninstall -g cobaltians
    sudo npm install -g cobaltians

Or you can try to fix the problem by installing nodegit with `sudo npm install -g nodegit` and re-run the cobaltians command to create your app.

Or maybe you just don't have Git installed on your computer. In that case, download and install from [the git website](https://git-scm.com/)

I hope this will help,
Cheers

**Comment by andresetevejob** [comment]
Hi Guillaume, 
I try your solution and I will make a feedback.Do you speak french?

**Comment by ggendre** [comment]
oui. n'hésites pas si tu as le moindre problème.

**Comment by andresetevejob** [comment]
![nodegiterror](https://cloud.githubusercontent.com/assets/3342068/9657071/c9fe66a8-5235-11e5-8a2d-fed246cf83a5.JPG)
Bonjour guillaume, j'ai suivi ce que tu as dis j'ai d'abord desintallé cobaltians ensuite j'essai d'installé nodegit mais j'ai cette erreur en capture d'ecran.J' ai git déja installé sur ma machine c'est une version 1.8

**Comment by ggendre** [comment]
hello

Ta version de nodejs semble un peu vieille. ya eu pas mal de changement après la 0.10.32. 
npm est mis à jour encore plus souvent donc je te conseille de réinstaller node puis de t'assurer que tu as bien la dernière version de npm avec cette commande :

    sudo npm install npm -g

la commande npm -v doit te donner un numéro plus gros que 2.1.8.
Une fois que tu as fait ça, rebelotte, désinstalle et réinstalle cobatians. ;)

---
More on node.js and npm updating here : https://docs.npmjs.com/getting-started/installing-node

**Comment by andresetevejob** [comment]
Bonjour Guillaume,
![cobalterror](https://cloud.githubusercontent.com/assets/3342068/9682799/fdf9f75c-5301-11e5-84cb-55caac04e391.JPG)

J'espère que tu vas très bien.J'ai suivi tes instructions mais j'ai une nouvelle erreur

**Comment by ggendre** [comment]
Bon déjà tout s'est bien installé, c'est pas mal. par contre le problème de chemin c'est pas normal. j'avai pas le problème sous mac. je récupère un windows ce soir et je te redis.

**Comment by andresetevejob** [comment]
Apparemment le changement de version de node est venu mettre en péril le fonctionnement de la commande ionic serve sur machine.Elle me genere des erreurs lorsque j'essai de tester mes app ionci avec le livereload
![erreurnode](https://cloud.githubusercontent.com/assets/3342068/9689425/d78510da-532d-11e5-865c-b7f4ce038644.JPG)

**Comment by mywaystar** [comment]
Je conseille d'utiliser nvm pour gérer les versions de node.  

-----Message d'origine-----
De : "andresetevejob" <notifications@github.com>
Envoyé : ‎04/‎09/‎2015 18:53
À : "cobaltians/Cobalt" <Cobalt@noreply.github.com>
Objet : Re: [Cobalt] Error cobalt create project (#35)

Apparemment le changement de version de node est venu mettre en péril le fonctionnement de la commande ionic serve sur machine.Elle me genere des erreurs lorsque j'essai de tester mes app ionci avec le livereload

**Comment by andresetevejob** [comment]
Guillaume,
Vraiment merci beaucoup nvm marche tres bien mon probleme de version de node est resolue.J'attends maintenant que tu me donnes la solution pour Cobalt.J'aimerais savoir si tu es un developpeur Javascript? ou quels sont les langages dans lesquels tu developpes

**Comment by ggendre** [comment]
Je suis développeur web mobile donc javascript oui.
C'est moi qui ait fait la dernière mise a jour du CLI cobaltians lors de la dernière release de Cobalt il y a quelques semaines. Je viens de tester de mon coté, je reproduit le problème sous Windows et pas sous linux/mac. ça doit être un problème de chemin, je vais corriger ça ASAP.

En attendant si tu veux tester rapidement le helloworld tu peux le builder à partir des sources en suivant la marche à suivre indiquée [ici](https://github.com/cobaltians/Cobalt/wiki/Samples-list).
En résumé :

    git clone https://github.com/Cobaltians-Samples/Samples-HelloWorld-Android.git

Puis dans le dossier cloné : `git submodule init` puis `git submodule update`. En esperant que ça te dépanne en attendant la correction.

**Comment by andresetevejob** [comment]
ok merci beaucoup je suis à  l'ecoute pour les mises à jours.Mais j'aimerais te poser deux autres questions comment faudrait t'il s'y prendre pour concevoir un framework tel que Cobalt?.Est-ce possible que je puisse travailler avec vous sur l'amelioration du framework Cobalt?

**Comment by ggendre** [comment]
Pour concevoir un framework comme Cobalt from scratch ce n'est pas du tout évident. Le plus simple c'est de l'utiliser ;)
Pour contribuer à Cobalt, pas de problème nous cherchons justement des contributeurs pour travailler avec nous sur le projet. Jette un oeil à la page [Contribute](https://github.com/cobaltians/cobalt/wiki/Contribute) du wiki et envoie nous un petit mail si t'es intéressé :)

**Comment by ggendre** [comment]
Hello,
Le bug de la ligne de commande à été corrigé. La commande `cobaltians create` est à nouveau utilisable.

Mettre a jour la ligne de commande cobaltians au préalable :

    npm update -g cobaltians

**Comment by andresetevejob** [comment]
Hi Gendre,
J'ai envoyé un mail de contribution au développement de cobalt à l'adresse contact@cobaltians.org.J'attends votre retour

**Comment by gcallejo** [comment]
Bonjour,
Je me permets de poster à la suite car j'ai le même message d'erreur que celui signalé plus haut lors de la création de l'application Hello World (je suis sous MacOS):
Error { [Error: Cannot find module '../build/Debug/nodegit.node'] code: 'MODULE_
NOT_FOUND' }
Pourtant, j'ai une version tout à fait récente de Node et j'ai Git installé sur ma machine. Du coup, est-ce qu'il est nécessaire d'installer nodegit pour que cela fonctionne ou le fix est-il supposé s'en affranchir (j'ai lu qu'il était en théorie automatiquement installé lors du processus) ?
Merci d'avance

**Comment by ggendre** [comment]
@gcallejo : nodegit est pourtant dans le package.json du packet [cobaltians](https://www.npmjs.com/package/cobaltians) donc a part des problèmes de version de nodejs ou de npm je vois pas trop d'où ça peut venir.

Pouvez vous @gcallejo et @andresetevejob m'envoyer les résultats de la commande suivante chez vous ? 

    npm -v && node -v

De mon côté je suis en node v0.12.7 et npm 2.11.3

**Comment by gcallejo** [comment]
Pour moi, npm 2.14.2 et node v4.0.0
Je suis allé vérifier le package.json de cobaltians, il a bien la dépendance nodegit, cela devrait fonctionner. Ou alors il y a un souci avec les  versions 4.x de Node ? Je vais essayer avec ta version pour voir

**Comment by gcallejo** [comment]
Bon je crois qu'on a trouvé, la création s'est parfaitement passée avec la version 0.12.7 de Node gérée avec nvm.
Visiblement il y a donc un vrai souci avec les dernières versions, je vais rester avec  celle-là pour l'instant du coup.
Merci pour ton aide ;)

Gonz

**Comment by ggendre** [comment]
Ok merci pour l'info!
La nouvelle version de nodejs est encore toute fraiche et ils ont fait un passage de 2.14 à 4.0 en moins de deux mois. Il y a une version qui date d'hier tout juste donc j'imagine que tous les packages sont pas compatible.
On va se pencher sur le problème dès qu'on a un peu de temps.

**Comment by andresetevejob** [comment]
Hi Guillaume, est-il possible de travailler correctement avec Cobalt en téléchargeant la version sur le site.Parce que avec les npm c'est toujours les memes problèmes.J'avais soumis un nouveau ticket mais apparemment je n'avais pas eu de suite

**Comment by ggendre** [comment]
Oui j'ai refermé ton autre issue et j'ai réouvert celle là. vu que c'est toujours le même problème.

Tu peux builder un sample de [cette liste](https://github.com/cobaltians/cobalt/wiki/Samples-list) en clonant le repository natif avec git puis un initialisant les submodules.

exemple avec le Catalog :

```
MacBook-Pro-de-Guillaume:~ guillaume$ git clone https://github.com/Cobaltians-Samples/Samples-Catalog-Android.git
Cloning into 'Samples-Catalog-Android'...
remote: Counting objects: 856, done.
remote: Total 856 (delta 0), reused 0 (delta 0), pack-reused 856
Receiving objects: 100% (856/856), 319.29 KiB | 212.00 KiB/s, done.
Resolving deltas: 100% (378/378), done.
Checking connectivity... done.

MacBook-Pro-de-Guillaume:~ guillaume$ cd Samples-Catalog-Android/

MacBook-Pro-de-Guillaume:Samples-Catalog-Android guillaume$ git submodule update --init
Submodule 'Catalog/src/main/assets/www/LocationPlugin' (git://github.com/cobaltians-plugins/plugins-Location-Web.git) registered for path 'Catalog/src/main/assets/www/LocationPlugin'
[...]
//initing all submodules
```

ensuite tu n'a plus qu'à ouvrir le projet avec android studio en sélectionnant le choix "Import project (eclipse, adt, etc)" puis le dossier Samples-Catalog-Android juste créé

Si tu veux ajouter Cobalt à un projet android existant c'est un poil plus complexe mais [la doc est là](https://github.com/cobaltians/cobalt/wiki/Android-Setup)

**Comment by andresetevejob** [comment]
Merci beaucoup, je crois que je vais me pencher vers cette solution et te faire un retour

**Comment by dimitrivalax** [comment]
Merci guillaume, ça fonctionne.

Je vais pourvoir essayer...

**Comment by davidc2k3** [comment]
Hi, also encountered this error, using Mac OS X Yosemite.

$ sudo cobaltians create myApp HelloWorld
Would you like to create an iOS app y/n  (default: y): 
Would you like to create an Android app y/n  (default: y): 
Info creating path myApp
Error { [Error: Cannot find module '../build/Debug/nodegit.node'] code: 'MODULE_NOT_FOUND' }

Do i need to create on particular folder?

Thanks in advance.

**Comment by ggendre** [comment]
Hi,

No, that's not a folder issue. It is because the nodegit package doesn't work for node > v0.12, and you probably have node 4 or 5 on your mac.

To have multiple nodeJs version on your computer, install [nvm](https://github.com/creationix/nvm), then run 
```
nvm install 0.12
nvm use 0.12
```

and then re-run `npm install -g cobaltians` and try the `create` command again. It should work better :)

**Comment by davidc2k3** [comment]
Hi ggendre,

Thanks a lot, it works!
I uninstall node 5 and installed 0.12.

$ sudo cobaltians create myApp HelloWorld
Would you like to create an iOS app y/n  (default: y): 
Would you like to create an Android app y/n  (default: y): 
Info creating path myApp
Info creating path myApp/iOS
Info Cloning https://github.com/Cobaltians-Samples/Samples-HelloWorld-iOS.git
Success repository https://github.com/Cobaltians-Samples/Samples-HelloWorld-iOS.git cloned
Success getting submodules for myApp/iOS/myApp
Success Fetching submodules from .gitmodules
Success got submodule 'Cobalt'
Success submodule init worked
Success submodule update worked
Success got submodule 'www/common'
Success submodule init worked
Success submodule update worked
Success got submodule 'www/platform'
Success submodule init worked
Success submodule update worked
Success submodule init ended
Info creating path myApp/Android
Info Cloning https://github.com/Cobaltians-Samples/Samples-HelloWorld-Android.git
Success repository https://github.com/Cobaltians-Samples/Samples-HelloWorld-Android.git cloned
Success getting submodules for myApp/Android/myApp
Success Fetching submodules from .gitmodules
Success got submodule 'cobalt'
Success submodule init worked
Success submodule update worked
Success got submodule 'HelloWorld/src/main/assets/www/common'
Success submodule init worked
Success submodule update worked
Success got submodule 'HelloWorld/src/main/assets/www/platform'
Success submodule init worked
Success submodule update worked
Success submodule init ended
Info making the template for iOS
Info making the template for Android
Info Create cobaltians file
Success Finished

**Comment by ggendre** [comment]
Hi all,

CLI has been fixed and now works on node 4.2.4 (LTS) and 5.4.1. No need to come back to an old node version anymore.

To update your node run `nvm install stable` or follow [these instructions](https://docs.npmjs.com/getting-started/installing-node#updating-npm) then update the cobaltians CLI by running `npm install -g cobaltians` again

have fun ;)
