### ISSUE TITLE
Erreur Cobalt

### ISSUE THREAD

**Issue by andresetevejob** [cobaltians/Cobalt#36]
Hi All, 
meme apres un npm update -g cobaltians j'ai toujours des erreurs lors de la creation d'une application avec cobalt
![erreurcobalt](https://cloud.githubusercontent.com/assets/3342068/9723734/43c3603c-55c0-11e5-8c27-03c1b6db2454.JPG)

**Comment by ggendre** [comment]
J'ai réouverte l'issue https://github.com/cobaltians/Cobalt/issues/35 donc je ferme celle là. on va essayer de pas faire de doublons ;)
