### ISSUE TITLE
Facebook Connect plugin?

### ISSUE THREAD

**Issue by giji** [cobaltians/Cobalt#38]
Hello 
is it possible to do Native fb login with cobalt ? if yes what would be scenario?

**Comment by ggendre** [comment]
Hi Giji,

There is no Facebook Connect plugin available with Cobalt yet. That's one of the first we will do but we just have some outdated code for the moment so we can't release it now.

Anyway if you want to build it we suggest that you add Facebook connect SDK in your native app as described [here for iOS](https://developers.facebook.com/docs/facebook-login/ios) and [here for Android](https://developers.facebook.com/docs/facebook-login/android) and the use Cobalt [events](https://github.com/cobaltians/cobalt/wiki/Introduction-to-Cobalt-Events) or Cobalt [plugin](https://github.com/cobaltians/cobalt/wiki/Plugins-creation) to interact between web and native.

I admit that if you don't have native skills you will probably get lost in the process. We would be glad to help you in the process if you need it.

Guillaume

**Comment by giji** [comment]
Hi GGendre 

thanks for tip, will dig in issue and come back  with questions .

**Comment by mywaystar** [comment]
It's possible to do facebook connect with the current release by doing a native login view and then i used the native facebook sdk. When it's logged, you have just to switch to a cobalt view, and you can send to it the facebook token you got with the SDK.
