### ISSUE TITLE
Hello World failed to run on Android Studio 1.4.1

### ISSUE THREAD

**Issue by davidc2k3** [cobaltians/Cobalt#39]
Hi,

Newbie here ;)
I just succesfully built Hello World Android sample:

$ sudo cobaltians create cobalt-helloworld HelloWorld
Password:
Would you like to create an iOS app y/n  (default: y): n
Would you like to create an Android app y/n  (default: y): 
Info creating path cobalt-helloworld
Info creating path cobalt-helloworld/Android
Info Cloning https://github.com/Cobaltians-Samples/Samples-HelloWorld-Android.git
Success repository https://github.com/Cobaltians-Samples/Samples-HelloWorld-Android.git cloned
Success getting submodules for cobalt-helloworld/Android/cobalt-helloworld
Success Fetching submodules from .gitmodules
Success got submodule 'cobalt'
Success submodule init worked
Success submodule update worked
Success got submodule 'HelloWorld/src/main/assets/www/common'
Success submodule init worked
Success submodule update worked
Success got submodule 'HelloWorld/src/main/assets/www/platform'
Success submodule init worked
Success submodule update worked
Success submodule init ended
Info making the template for Android
Info Create cobaltians file
Success Finished

But when imported to Android Studio 1.4.1 on Mac OS X El Capitan, it failed to run with these messages:

![screen shot 2015-11-12 at 4 10 19 pm](https://cloud.githubusercontent.com/assets/5120343/11114630/a44368c8-8958-11e5-86e7-9e446ed29f0e.png)

Any help appreciated.

Thanks

**Comment by ggendre** [comment]
Hi !

Maybe you just opened hte project the wrong way : Did you clic on "Import project (Eclipse, Gradle)" or "Import existing Android studio project" ?

The good one is "Import project (Eclipse, Gradle)" :

<img width="508" alt="capture d ecran 2015-11-12 a 10 27 02" src="https://cloud.githubusercontent.com/assets/534697/11115024/13fb1d30-8929-11e5-9024-87e09d654824.png">

tell me if it's better

**Comment by davidc2k3** [comment]
Hi ggendre,

Thanks for ultra fast response!
Yes, I selected that option, here are my steps below:

![screen shot 2015-11-12 at 4 38 34 pm](https://cloud.githubusercontent.com/assets/5120343/11115327/4e93bc0c-895d-11e5-835c-f72ad945700c.png)
![screen shot 2015-11-12 at 4 39 23 pm](https://cloud.githubusercontent.com/assets/5120343/11115328/4e96133a-895d-11e5-9b50-f1361d8731f8.png)
![screen shot 2015-11-12 at 4 39 40 pm](https://cloud.githubusercontent.com/assets/5120343/11115329/4eb1672a-895d-11e5-80c3-ad68a52b5da4.png)
![screen shot 2015-11-12 at 4 39 58 pm](https://cloud.githubusercontent.com/assets/5120343/11115330/4eb57cd4-895d-11e5-8d20-a2e5adad0def.png)
![screen shot 2015-11-12 at 4 40 18 pm](https://cloud.githubusercontent.com/assets/5120343/11115347/7bc066c6-895d-11e5-8c18-00790dd6e9f8.png)
![screen shot 2015-11-12 at 4 41 03 pm](https://cloud.githubusercontent.com/assets/5120343/11115343/7b445888-895d-11e5-8e56-b97f53de5572.png)
![screen shot 2015-11-12 at 4 41 47 pm](https://cloud.githubusercontent.com/assets/5120343/11115345/7b4aa062-895d-11e5-907a-cd9aa19d1a6e.png)
![screen shot 2015-11-12 at 4 42 01 pm](https://cloud.githubusercontent.com/assets/5120343/11115344/7b472d56-895d-11e5-8f34-5010845fab52.png)
![screen shot 2015-11-12 at 4 42 26 pm](https://cloud.githubusercontent.com/assets/5120343/11115346/7ba17cac-895d-11e5-918e-cd19c6a3aec4.png)

**Comment by ggendre** [comment]
On step 2, choose "Import project from existing model" and select gradle. It should work better.

**Comment by davidc2k3** [comment]
it works!

BIG THANKS to you ggendre :))

![screen shot 2015-11-12 at 10 40 47 pm](https://cloud.githubusercontent.com/assets/5120343/11122633/a58cd21a-898e-11e5-9f20-a325c6201eb1.png)

**Comment by ggendre** [comment]
You're welcome ! Have fun :)

Don't hesitate to ask if you get stuck on something else later :)
