### ISSUE TITLE
Camera access for IOS and Android?

### ISSUE THREAD

**Issue by davidc2k3** [cobaltians/Cobalt#40]
Hi,

I'm a developer for classifieds/ads posting website at http://www.pasarindo.com
I have tried unsuccessfully using appgeyser and como to convert to IOS/Android mobile app, since they are unable to access mobile camera for taking pictures.
Any step-by-step guide to convert to Cobalt and be able to use mobile camera will be greatly appreciated.

TIA

**Comment by mywaystar** [comment]
it's possible. I did WebRTC using cobalt, and i did a system to take pictures.

What you have to do, is to send an event from the javascript side, to the native side, like "takePicture".
You catch it on the native side, and the,, you can you a code sample like this one: http://www.theappguruz.com/blog/android-take-photo-camera-gallery-code-sample

**Comment by davidc2k3** [comment]
Thanks!

I will give this a try.
