### ISSUE TITLE
better cobalt.platform

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#46]
- [x] cobalt.platform.name should contain "Android" or "iOS"

also add two booleans :
- [x]  cobalt.platform.isiOS
- [x]  cobalt.platform.isAndroid
- [x] update doc on develop

**Comment by ggendre** [comment]
@TDanielK : something more to do on this feature ? or can we close the issue ?

**Comment by TDanielK** [comment]
We can close the issue.
