### ISSUE TITLE
Cobalt Storage v3

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#56]
more for cobalt.storage
- [ ] add cobalt.sessionStorage or expiry to keys
- [ ] use a real bdd for iOS
- [ ] enable storage access from Android
- [ ] enable storage access from iOS
- [ ] possibility to use your own database system on Android
- [ ] possibility to use your own database system on iOS
- [ ] update documentation Android
- [ ] update documentation iOS
- [ ] update documentation Web

**Comment by Doc1faux** [comment]
Will not be implemented like this
