### ISSUE TITLE
web browser as a platform

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#63]
Rework web code and remove `debugInBrowser` in profit of a platform version of cobalt built for the web 

Could be useful for debugging and for mobile websites built on cobalt

**Comment by lduboeuf** [comment]
:+1:

**Comment by lduboeuf** [comment]
apart from the Iframe solution to handle cobalt.navigation between views, could be nice to . have somthing like a web container that can fetch and append content in a div container. maybe some parts of this projects may help https://github.com/luruke/barba.js ( fetch a file and append it to a div container, use cached content and avoid reloadings of assets )

**Comment by ggendre** [comment]
debugInBrowser is dynamic now, you can use cobalt on web files without pb (with debug=false)
