### ISSUE TITLE
all packages should be org.cobaltians

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#75]
There is a mix of cobaltians.com or cobaltians.fr in Cobalt core, plugins and samples both for iOS and Android.

**Comment by Myrdhinn** [comment]
android, done in :
cobalt branche dev-nativeBars
sample sideMenu
appInfosPlugin branche dev-nativeBars
actionPickerPlugin branche dev-nativeBars
pubSubPlugin branche dev-nativeBars
