### ISSUE TITLE
Make iOS Framework

### ISSUE THREAD

**Issue by Doc1faux** [cobaltians/Cobalt#78]
Cleanup the iOS core to create an iOS Framework of Cobalt

- [x] make the iOS Framework
- [x] use it in every samples in develop or dev-nativeBars branches (except for catalog sample)
- [x] update wiki on how to add cobalt to an iOS project

**Comment by ggendre** [comment]
updatied the issue with a checklist and sent it back to in-progress (wiki update todo if I remember well)
