### ISSUE TITLE
Releasing Cobalt 0.5

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#79]
A "small" checklist for the release

update version numbers to `0.5.0`
- [x] in iOS sources on develop
- [x] in Android sources on dev-nativeBars
- [x] in Web sources on develop

merging dev-nativeBars to develop for **core** repos:

- [x] Android : git merge dev-nativeBars to develop for Cobalt-Android
- [x] iOS : git merge dev-nativeBars to develop for Cobalt-iOS
- [x] iOS framework : update budnle and stuff from Cobalt-iOS develop branch
- [x] Web : git merge dev-nativeBars to develop for Cobalt-Web
- [x] Core parent repo : git merge dev-nativeBars to develop and ensure submodules are fine for all OSs

merging dev-nativeBars to develop for **samples** repos:

- [x] Web : git merge dev-nativeBars to develop for all samples and ensure develop is used in all submodules
- [x] Android : git merge dev-nativeBars to develop in HelloWorld and ensure develop is used in all submodules
- [x] Android : git merge dev-nativeBars to develop in Catalog and ensure develop is used in all submodules
- [x] Android : git merge dev-nativeBars to develop in SideMenu and ensure develop is used in all submodules
- [x] iOS : git merge dev-nativeBars to develop in HelloWorld and ensure develop is used in all submodules
- [x] iOS : git merge dev-nativeBars to develop in Catalog and ensure develop is used in all submodules
- [x] iOS : git merge dev-nativeBars to develop in SideMenu and ensure develop is used in all submodules
- [x] iOS : in SideMenu sample, update cobalt iOS repository to latest develop
- [x] iOS : in Catalog sample, update cobalt iOS repository to latest develop
- [x] iOS : in HelloWorld sample, update cobalt iOS repository to latest develop

creating develop and master branch for plugins :

- [x] Web : for all plugins, create a develop branch and a master branch from 0.4.1 
- [x] iOS : for all plugins, create a develop branch and a master branch from 0.4.1 
- [x] Android : for all plugins except location, create a develop branch and a master branch from dev-nativeBars 
- [x] Android : for location plugin, merge dev-nativeBars to develop and create a master branch from develop

creating or updating **master branches** :

- [x] Web : create a master branch from develop or merge it from develop for core repositories
- [x] Web : create a master branch from develop or merge it from develop for plugins repositories
- [x] Web : create a master branch from develop or merge it from develop for samples repositories
- [x] Android : create a master branch from develop or merge it from develop for core repository
- [x] iOS : create a master branch from develop or merge it from develop for core repositories
- [x] Core parent : create a master branch from develop or merge it 
from develop for core parent repository
- [x] Plugins parent : create a master branch from develop or merge it from develop for all plugins parent repository

creating develop branch for fonts :

- [x] iOS : for all fonts, create a develop branch from master
- [x] Android : for all fonts, create a develop branch from master

Wiki
- [x] Update current version in Roadmap on the wiki in dev-nativeBars branch
- [x] wiki : merge branches to develop

delete dev-nativeBars from all repositories (including wiki) 
- [x] web core repositories
- [x] web plugins repositories
- [x] web samples repositories
- [x] web fonts repositories
- [x] web core repositories
- [x] android plugins repositories
- [x] android samples repositories
- [x] android fonts repositories
- [x] iOS core repositories
- [x] iOS plugins repositories
- [x] iOS samples repositories
- [x] iOS fonts repositories
- [x] wiki

Releasing !

- [x] Write release notes
- [x] Write blog article
- [x] Check release notes are complete
- [x] Check blog article is perfect
- [x] Ensure all repositories are on master by default
- [x] Merge wiki develop into master
- [x] Close issues or move unfinished issues from release
- [x] Create zip file with cloned cobalt grand-parent repo
- [x] update website current version and zip file url in develop branch
- [x] apply develop website branch to master and update server
- [x] Publish release
- [x] Publish blog article
- [x] Make a party !

cleanup, delete 0.4.1 from all repositories (including wiki) 
- [x] web core repositories
- [x] web plugins repositories
- [x] web samples repositories
- [x] web fonts repositories
- [x] web core repositories
- [x] web CLI repository
- [x] android plugins repositories
- [x] android samples repositories
- [x] android fonts repositories
- [x] iOS core repositories
- [x] iOS plugins repositories
- [x] iOS samples repositories
- [x] iOS fonts repositories
- [x] wiki

**Comment by Doc1faux** [comment]
Make a party checkbox has been moved to issue #87
