### ISSUE TITLE
drop iOS6 support

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#82]
We have a lot of code for iOS6 support. 
According to [Apple](https://developer.apple.com/support/app-store/), iOS7 and below are now (05/2016) 5% of devices.
According to [this site](https://david-smith.org/iosversionstats/) iOS6 is under 3%.

**get rid or iOS6 support**
- [x] in web core code on branch issue-82.
- [x] update web submodule in Catalog Sample on branch issue-82.
- [x] quick test tour on catalog
- [x] in iOS code  on branch issue-82
- [x] update iOS submodule in Catalog Sample on branch issue-82.
- [x] iOS fix weblayer issue
- [x] merge branches to develop on Cobalt-Web-Sources and Cobalt-Web-iOS
- [x] merge branch to develop on Cobalt-iOS and update Cobalt-iOS-Framework
- [x] merge branch to develop on Samples-Catalog-iOS
- [x] write a topo about this for the release

**Comment by ggendre** [comment]
Quick test tour results on Catalog Sample after web has removed iOS6 support on device : iPhone 5 simulator, iOS9.3.
- Everything works fine (navigation, events, callbacks,  auto tests, etc) **except weblayers** :: they open fine but can't be closed.

**Comment by Doc1faux** [comment]
Tested on iPhone 6 Plus iOS 9.3.2, iPhone 4S iOS 8.2 and iPhone 4 iOS 7.1.2 and all works like a charm.

**Comment by Doc1faux** [comment]
Cobalt-iOS merged and Cobalt-iOS-Framework regenerated.
Merge conflict on Cobalt-Web-iOS so I let you fix it @ggendre.

**Comment by ggendre** [comment]
web repositories are now merged to develop.
I update catalog submodule on both `issue-82` and `develop` to use latest `develop` web sources.
I noticed a trouble with font in `issue-82` branch of the catalog but it may be just not up to date from develop.

**Comment by Doc1faux** [comment]
FontAwesome was up-to-date on `develop` but not on `issue-82` ;)

**Comment by ggendre** [comment]
- Branch `issue-82` from `Samples-Catalog-iOS` has been merged on `develop` and deleted.
- Branch `issue-82` form `Cobalt-iOS` was already merged on `develop`. I deleted it.
- I wrote a topo on this issue in the release draft.

sector clear. closing.
