### ISSUE TITLE
nativeBars - enable user to enable/disable animation

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#88]
on iOS an animation can be done when the bars are changing. 
Since [this commit](https://github.com/cobaltians/Cobalt-iOS/commit/646ad2d528d764099cf8f8d2f0824223f0858119) (on develop, after the 0.5 release) the animation has been turned off. 
We should be able to enable animation if we want.

on develop branches :
- [ ] add boolean into web part
- [ ] add boolean into documentation
- [ ] add boolean into iOS part
- [ ] check that there is no need of such boolean on android

**Comment by ggendre** [comment]
I updated the issue because of the change occured in commit https://github.com/cobaltians/Cobalt-iOS/commit/646ad2d528d764099cf8f8d2f0824223f0858119 that disabled bars animation by default

**Comment by Doc1faux** [comment]
Or not, because it can lead to crashes on iOS8 if any setBars or setActionX method is spammed from the Web.

**Comment by ggendre** [comment]
wont do
