### ISSUE TITLE
When a Web layer request keyboard on loading, keyboard blink or not showing

### ISSUE THREAD

**Issue by Doc1faux** [cobaltians/Cobalt#9]
when a webLayer has à $('#myInput').focus() on html load :

on ios 7 : keyboard might show and hide itself quickly
on Android : keyboard is not shown on some devices I think (double-check this)...

**Comment by Doc1faux** [comment]
Works well on Android, except under Android 4.1...
Tested on:
- HTC Wildfire running Android 2.2.1,
- Galaxy Nexus running Android 4.0.4,
- Samsung Galaxy S5 running Android 5.0, 
- Nexus 7 running Android 5.1,
- Nexus 4 running Android 5.1.1.

On iOS, all devices and versions are affected :(

The timeout does not always work.
I tried to trigger the focus on an event receipt sent when the WebView alerts the native that it is completely loaded but nothing changed...

I do not have other ideas...

**Comment by ggendre** [comment]
increased timeout to 350ms instead of 200. works fine on all our devices ;)

**Comment by ggendre** [comment]
If we want to make a better fix we will have to have a `onPageShown` event in weblayers webviews. maybe in the next refactoring ? ;)
