### ISSUE TITLE
Catalog - action picker not working

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#91]
The Action Picker is not working in the Plugins section of the Catalog on master.

find why and fix this on develop if needed.

**Comment by Myrdhinn** [comment]
fixed on Android, todo on iOS (add submodule and bind to project)

**Comment by Doc1faux** [comment]
What are you saying ?!? The ActionPicker is working fine on iOS Catalog...

**Comment by ggendre** [comment]
Not on master I think
Le mar. 12 avr. 2016 à 13:47, Sébastien Vitard <notifications@github.com> a
écrit :

**Comment by ggendre** [comment]
I confirm it works well now.

**Comment by ggendre** [comment]
It was probably just a submodule issue I had when delivering the Catalog app on the appStore
